### ISSUE TITLE
[flow] error parsing source for `Element<*>`

### ISSUE THREAD

**Issue by rosskevin** [reactjs/react-docgen#181]
This is valid flow syntax:

```javascript
component?: string | Function | Element<*>
```
It breaks when Element has the `<*>`, which flow requires otherwise it complains with:

```
Element. Application of polymorphic type needs <list of 1 argument>. (Can use `*` for inferrable ones)
```

Error:
```
Error parsing src for Hidden
{ SyntaxError: Unexpected token (25:42)
    at Parser.pp.raise (/Users/kross/projects/material-ui/node_modules/react-docgen/node_modules/babylon/lib/parser/location.js:24:13)
    at Parser.pp.unexpected (/Users/kross/projects/material-ui/node_modules/react-docgen/node_modules/babylon/lib/parser/util.js:82:8)
    at Parser.pp.flowParsePrimaryType (/Users/kross/projects/material-ui/node_modules/react-docgen/node_modules/babylon/lib/plugins/flow.js:552:8)
    at Parser.pp.flowParsePostfixType (/Users/kross/projects/material-ui/node_modules/react-docgen/node_modules/babylon/lib/plugins/flow.js:557:38)
    at Parser.pp.flowParsePrefixType (/Users/kross/projects/material-ui/node_modules/react-docgen/node_modules/babylon/lib/plugins/flow.js:573:17)
    at Parser.pp.flowParseIntersectionType (/Users/kross/projects/material-ui/node_modules/react-docgen/node_modules/babylon/lib/plugins/flow.js:579:19)
    at Parser.pp.flowParseUnionType (/Users/kross/projects/material-ui/node_modules/react-docgen/node_modules/babylon/lib/plugins/flow.js:589:19)
    at Parser.pp.flowParseType (/Users/kross/projects/material-ui/node_modules/react-docgen/node_modules/babylon/lib/plugins/flow.js:600:19)
    at Parser.pp.flowParseTypeParameterInstantiation (/Users/kross/projects/material-ui/node_modules/react-docgen/node_modules/babylon/lib/plugins/flow.js:217:27)
    at Parser.pp.flowParseGenericType (/Users/kross/projects/material-ui/node_modules/react-docgen/node_modules/babylon/lib/plugins/flow.js:364:32) pos: 594, loc: Position { line: 25, column: 42 } }
```

Branch: https://github.com/alienfast/material-ui/commit/9c5a3b6cb245b67e20aa4e6e1dbf7e6662aadde3
Source: https://github.com/alienfast/material-ui/blob/69059093c454fc7b1e84c22bf25013316ad6226b/src/Hidden/Hidden.js

Reproduce with `yarn build:docs`.

Is this something that needs to be reported elsewhere?

**Comment by fkling** [comment]
Which version of react-docgen are you using?

**Comment by rosskevin** [comment]
`react-docgen@2.14.1`

**Comment by fkling** [comment]
Ah... v2 uses an old Babel version that doesn't understand new flow type annotations. Give the v3 beta version a try!

**Comment by rosskevin** [comment]
`3.0.0.beta4` worked, thanks!
