### ISSUE TITLE
Error when running v2.19.0

### ISSUE THREAD

**Issue by bsmith-cycorp** [reactjs/react-docgen#219]
I get the following when trying to run the latest release:

```
module.js:474
    throw err;
    ^

Error: Cannot find module '../dist/main'
    at Function.Module._resolveFilename (module.js:472:15)
    at Function.Module._load (module.js:420:25)
    at Module.require (module.js:500:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/bsmith/svn/cyc/doc/app/src/cyc-ui/src/projects/component-documentation/node_modules/react-docgen/bin/react-docgen.js:61:14)
    at Module._compile (module.js:573:32)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
    at Function.Module._load (module.js:441:3)
```

**Comment by bsmith-cycorp** [comment]
Full log:

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/Cellar/node/7.1.0/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'run',
1 verbose cli   'build:doc' ]
2 info using npm@5.3.0
3 info using node@v7.1.0
4 verbose run-script [ 'prebuild:doc', 'build:doc', 'postbuild:doc' ]
5 info lifecycle component-documentation@1.0.0~prebuild:doc: component-documentation@1.0.0
6 info lifecycle component-documentation@1.0.0~build:doc: component-documentation@1.0.0
7 verbose lifecycle component-documentation@1.0.0~build:doc: unsafe-perm in lifecycle true
8 verbose lifecycle component-documentation@1.0.0~build:doc: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Users/bsmith/svn/cyc/doc/app/src/cyc-ui/src/projects/component-documentation/node_modules/.bin:/Users/bsmith/bin:/Users/bsmith/.npm_global/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin
9 verbose lifecycle component-documentation@1.0.0~build:doc: CWD: /Users/bsmith/svn/cyc/doc/app/src/cyc-ui/src/projects/component-documentation
10 silly lifecycle component-documentation@1.0.0~build:doc: Args: [ '-c',
10 silly lifecycle   'react-docgen ../../lib/components/*/*.react.js --pretty -e index.js --resolver findAllComponentDefinitions -o ./documentation-data.json' ]
11 silly lifecycle component-documentation@1.0.0~build:doc: Returned: code: 1  signal: null
12 info lifecycle component-documentation@1.0.0~build:doc: Failed to exec build:doc script
13 verbose stack Error: component-documentation@1.0.0 build:doc: `react-docgen ../../lib/components/*/*.react.js --pretty -e index.js --resolver findAllComponentDefinitions -o ./documentation-data.json`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:289:16)
13 verbose stack     at emitTwo (events.js:106:13)
13 verbose stack     at EventEmitter.emit (events.js:191:7)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:40:14)
13 verbose stack     at emitTwo (events.js:106:13)
13 verbose stack     at ChildProcess.emit (events.js:191:7)
13 verbose stack     at maybeClose (internal/child_process.js:885:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
14 verbose pkgid component-documentation@1.0.0
15 verbose cwd /Users/bsmith/svn/cyc/doc/app/src/cyc-ui/src/projects/component-documentation
16 verbose Darwin 16.7.0
17 verbose argv "/usr/local/Cellar/node/7.1.0/bin/node" "/usr/local/bin/npm" "run" "build:doc"
18 verbose node v7.1.0
19 verbose npm  v5.3.0
20 error code ELIFECYCLE
21 error errno 1
22 error component-documentation@1.0.0 build:doc: `react-docgen ../../lib/components/*/*.react.js --pretty -e index.js --resolver findAllComponentDefinitions -o ./documentation-data.json`
22 error Exit status 1
23 error Failed at the component-documentation@1.0.0 build:doc script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by bsmith-cycorp** [comment]
Apologies- something weird was happening and even though I deleted my `node_modules`, it was still installing v2.18.0.
