### ISSUE TITLE
Bug: parser error on static typed arrow functions

### ISSUE THREAD

**Issue by Flui** [reactjs/react-docgen#250]
when writing class functions using arrow notation and with static types annotated, the react-docgen parser throws an error at the colon before boolean. I am using **react-docgen@2.15.0**
`
_myclassfunction = (
    param1: string,
    param2: string
  ): boolean => {
 ...
}
`

> location.js:27
  throw err;
SyntaxError: Unexpected token (992:3)
    at Parser.pp.raise (/.../node_modules/react-docgen/node_modules/babylon/lib/parser/location.js:24:13)
    at Parser.pp.unexpected (/.../node_modules/react-docgen/node_modules/babylon/lib/parser/util.js:82:8)
    at Parser.pp.semicolon (/.../node_modules/react-docgen/node_modules/babylon/lib/parser/util.js:69:81)
    at Parser.pp.parseClassProperty (/.../node_modules/react-docgen/node_modules/babylon/lib/parser/statement.js:630:8)
    at Parser.parseClassProperty (/.../node_modules/react-docgen/node_modules/babylon/lib/plugins/flow.js:836:20)
    at Parser.pp.parseClass (/.../node_modules/react-docgen/node_modules/babylon/lib/parser/statement.js:567:32)
    at Parser.pp.parseStatement (/.../node_modules/react-docgen/node_modules/babylon/lib/parser/statement.js:84:19)
    at Parser.parseStatement (/.../node_modules/react-docgen/node_modules/babylon/lib/plugins/flow.js:655:22)
    at Parser.pp.parseTopLevel (/.../node_modules/react-docgen/node_modules/babylon/lib/parser/statement.js:30:21)
    at Parser.parse (/.../node_modules/react-docgen/node_modules/babylon/lib/parser/index.js:70:17)

**Comment by danez** [comment]
Please try using latest beta version of 3.0.0 which should support the new syntax.
