### ISSUE TITLE
fails to detect components if used with recent react-intl

### ISSUE THREAD

**Issue by bartvde** [reactjs/react-docgen#29]
So when using recent react-intl (^2.0.0-pr-2), you need to change classes in a way that breaks react-docgen:

```
export default class HomeButton extends React.Component {
```

becomes:

```
import {defineMessages, injectIntl, intlShape} from 'react-intl';
class GeocodingResults extends React.Component {
}
export default injectIntl(GeocodingResults);
```

```
Error with path "js/components/HomeButton.test.js": Error: No suitable component definition found.
Error: No suitable component definition found.
    at parse (/Users/bartvandeneijnden/opengeo/git/sdk/node_modules/react-docgen/dist/parse.js:73:11)
    at Object.defaultParse [as parse] (/Users/bartvandeneijnden/opengeo/git/sdk/node_modules/react-docgen/dist/main.js:65:33)
    at /Users/bartvandeneijnden/opengeo/git/sdk/node_modules/react-docgen/bin/react-docgen.js:99:35
    at /Users/bartvandeneijnden/opengeo/git/sdk/node_modules/react-docgen/node_modules/node-dir/lib/readfiles.js:110:34
    at fs.js:334:14
    at FSReqWrap.oncomplete (fs.js:95:15)
```

Is there a way around this?
TIA.

**Comment by fkling** [comment]
You could either create your own resolver with the utility functions that react-docgen provides, or you could use the `findAllReactComponents` resolver.

However, I do think this use case is not uncommon and it might be worth it to have better support for this by default.

**Comment by bartvde** [comment]
@fkling where do I find the findAllReactComponents resolver?

**Comment by fkling** [comment]
https://github.com/reactjs/react-docgen/blob/master/src/resolver/findAllComponentDefinitions.js is what I mean.

**Comment by bartvde** [comment]
Ah thanks, a github search did not find this one.

**Comment by bartvde** [comment]
Thanks I managed to resolve my issue per your suggestion.

**Comment by bartvde** [comment]
Sorry to reopen this, but it seems it does not work in this case (with the extra argument):

```
export default injectIntl(AddLayer, {withRef: true});
```

?

**Comment by tizmagik** [comment]
@bartvde do you mind sharing where you landed with this? I'm having a similar issue and can't seem to use the component found by `findAllComponentDefinitions()`

**Comment by bartvde** [comment]
@tizmagik I'm using a small script, here is the code snippet:

```
var reactDocs = require('react-docgen');
var fs = require('fs');
var path = require('path');
var generateMarkdown = require('./generateMarkdown');

var dir = 'js/components/';
var output = 'docs/api/';

fs.readdir(dir, function(err, files) {
  if (err) {
    throw err;
  }
  files.forEach(function(file) {
    if (path.extname(file) === '.js' || path.extname(file) === '.jsx') {
      fs.readFile(dir + file, 'utf-8', function(err,src) {
        if (err) {
          throw err;
        }
        var componentInfo;
        try {
          componentInfo = reactDocs.parse(src, reactDocs.resolver.findAllComponentDefinitions);
        } catch(e) {
        }
        if (componentInfo  && componentInfo[0].description !== '') {
          var name = file.split('.')[0];
          var markdown = generateMarkdown(name, componentInfo[0]);
          fs.writeFileSync(output + name + '.md', markdown);
        }
      });
    }
  });
});
```
