### ISSUE TITLE
[Typescript] Cannot parse enums

### ISSUE THREAD

**Issue by redallen** [reactjs/react-docgen#355]
Components that use enums should have react-docgen just ignore them for now, I suppose.
```
SyntaxError: unknown: Unexpected token (8:12)

   6 | import { BaseSizes } from '../../styles/sizes';
   7 | 
>  8 | export enum TitleLevel {
     |             ^
   9 |   h1 = 'h1',
  10 |   h2 = 'h2',
  11 |   h3 = 'h3',
    at Object.raise (/home/redallen/src/patternfly-react/node_modules/@babel/parser/lib/index.js:6322:17)
    at Object.unexpected (/home/redallen/src/patternfly-react/node_modules/@babel/parser/lib/index.js:7638:16)
    at Object.parseExportFrom (/home/redallen/src/patternfly-react/node_modules/@babel/parser/lib/index.js:10978:14)
    at Object.parseExport (/home/redallen/src/patternfly-react/node_modules/@babel/parser/lib/index.js:10833:12)
    at Object.parseExport (/home/redallen/src/patternfly-react/node_modules/@babel/parser/lib/index.js:2225:24)
    at Object.parseStatementContent (/home/redallen/src/patternfly-react/node_modules/@babel/parser/lib/index.js:9867:27)
    at Object.parseStatement (/home/redallen/src/patternfly-react/node_modules/@babel/parser/lib/index.js:9763:17)
    at Object.parseStatement (/home/redallen/src/patternfly-react/node_modules/@babel/parser/lib/index.js:2019:26)
    at Object.parseBlockOrModuleBlockBody (/home/redallen/src/patternfly-react/node_modules/@babel/parser/lib/index.js:10340:25)
    at Object.parseBlockBody (/home/redallen/src/patternfly-react/node_modules/@babel/parser/lib/index.js:10327:10)
```

[This is the entire file.](https://github.com/reactjs/react-docgen/files/3157913/Title.txt)

Let me know how I can contribute @devongovett !

**Comment by devongovett** [comment]
Make sure your file is a .ts or .tsx file, and that. Pass the file name as an option to react-docgen otherwise it won’t know to enable typescript parsing.

**Comment by redallen** [comment]
That fixed it, awesome!
