### ISSUE TITLE
[Typescript] Cannot parse private/public fields of classes

### ISSUE THREAD

**Issue by redallen** [reactjs/react-docgen#356]
Like enums, these tokens can be discarded, but as someone using react-docgen I don't want to live that regex life!

```
SyntaxError: unknown: Unexpected token (22:9)

  20 | 
  21 | export class SkipToContent extends React.Component<SkipToContentProps> {
> 22 |   public static defaultProps = {
     |          ^
  23 |     component: 'a',
  24 |     className: '',
  25 |     show: false
    at Object.raise (/home/redallen/src/patternfly-react/node_modules/@babel/parser/lib/index.js:6322:17)
    at Object.unexpected (/home/redallen/src/patternfly-react/node_modules/@babel/parser/lib/index.js:7638:16)
    at Object.parseClassMemberWithIsStatic (/home/redallen/src/patternfly-react/node_modules/@babel/parser/lib/index.js:10711:12)
    at Object.parseClassMember (/home/redallen/src/patternfly-react/node_modules/@babel/parser/lib/index.js:10607:10)
    at withTopicForbiddingContext (/home/redallen/src/patternfly-react/node_modules/@babel/parser/lib/index.js:10562:14)
    at Object.withTopicForbiddingContext (/home/redallen/src/patternfly-react/node_modules/@babel/parser/lib/index.js:9657:14)
    at Object.parseClassBody (/home/redallen/src/patternfly-react/node_modules/@babel/parser/lib/index.js:10539:10)
    at Object.parseClass (/home/redallen/src/patternfly-react/node_modules/@babel/parser/lib/index.js:10513:22)
    at Object.parseStatementContent (/home/redallen/src/patternfly-react/node_modules/@babel/parser/lib/index.js:9805:21)
    at Object.parseStatement (/home/redallen/src/patternfly-react/node_modules/@babel/parser/lib/index.js:9763:17)
```

[SkipToContent.tsx](https://github.com/reactjs/react-docgen/files/3157953/SkipToContent.txt)

Again, let me know how I can contribute!

**Comment by redallen** [comment]
See #355
