### ISSUE TITLE
[Typescript] Cannot parse casting using `as`

### ISSUE THREAD

**Issue by redallen** [reactjs/react-docgen#357]
I assume at this point it's probably a babel plugin problem :)

 ```
SyntaxError: unknown: Unexpected token, expected "}" (22:37)

  20 |   ...props
  21 | }: AvatarProps) => (
> 22 |   <img {...props} src={src} alt={alt as string} className={css(styles.avatar, className)} />
     |                                      ^
  23 | );
  24 | 
    at Object.raise (/home/redallen/src/patternfly-react/node_modules/@babel/parser/lib/index.js:6322:17)
    at Object.unexpected (/home/redallen/src/patternfly-react/node_modules/@babel/parser/lib/index.js:7638:16)
    at Object.expect (/home/redallen/src/patternfly-react/node_modules/@babel/parser/lib/index.js:7624:28)
    at Object.jsxParseExpressionContainer (/home/redallen/src/patternfly-react/node_modules/@babel/parser/lib/index.js:3455:10)
    at Object.jsxParseAttributeValue (/home/redallen/src/patternfly-react/node_modules/@babel/parser/lib/index.js:3414:21)
    at Object.jsxParseAttribute (/home/redallen/src/patternfly-react/node_modules/@babel/parser/lib/index.js:3470:44)
    at Object.jsxParseOpeningElementAfterName (/home/redallen/src/patternfly-react/node_modules/@babel/parser/lib/index.js:3490:28)
    at Object.jsxParseOpeningElementAt (/home/redallen/src/patternfly-react/node_modules/@babel/parser/lib/index.js:3483:17)
    at Object.jsxParseElementAt (/home/redallen/src/patternfly-react/node_modules/@babel/parser/lib/index.js:3515:33)
    at Object.jsxParseElement (/home/redallen/src/patternfly-react/node_modules/@babel/parser/lib/index.js:3584:17)
```

A little simple example:
```
import * as React from 'react';

export interface AvatarProps {
  /** Attribute that specifies the alternate text of the image for the Avatar. */
  alt: string;
}

export const Avatar: React.SFC<AvatarProps> = ({
  alt
}: AvatarProps) => (
  <img alt={alt as string} />
);
```

**Comment by redallen** [comment]
See #355

**Comment by makmav** [comment]
How did you solve this problem
```javascript
docgen.parse(
    fs.readFileSync("./a.tsx"),
    docgen.resolver.findExportedComponentDefinition,
    docgen.defaultHandlers,
    {filename: 'to/babelrc'}
)

// my babel config
const { argv } = require('yargs');

module.exports = (api) => {
    const env = argv.env || [];
    const mode = !!env.find((value) => value === 'NODE_ENV=development')
        ? 'development'
        : 'production';

    api.cache.using(() => mode);

    return {
        presets: [
            [
                '@babel/preset-env',
                {
                    targets: {
                        browsers: ['>1%', 'last 4 versions', 'not ie < 9']
                    },
                    useBuiltIns: 'usage',
                    debug: false,
                    corejs: 3
                }
            ],
            '@babel/preset-react',
            '@babel/preset-typescript'
        ],
        plugins: [
            '@babel/plugin-syntax-dynamic-import',
            '@babel/plugin-proposal-class-properties',
            mode !== 'production' && 'react-refresh/babel'
        ].filter(Boolean),
        ignore: ['node_modules']
    };
};

```
it can't work
