### ISSUE TITLE
Error when parsing TypeScript types without comma

### ISSUE THREAD

**Issue by Sly321** [reactjs/react-docgen#376]
I have a bug when parsing TypeScript files that are missing the comma in the types.

```
"react-docgen": "^4.1.1"
node --version
v10.7.0
```

I have an example repository: https://github.com/Sly321/react-docgen-test

When i parse this file:

```tsx
import React, { ReactNode } from "react"

export type Props = {
    no: string
    /**
     * Some Description
     *
     * @type {ReactNode}
     * @memberof Props
     */
    children: ReactNode
    yes: string
}

export default function Anything({  }: Props) {
    return <div>content</div>
}
```

With this command:

```js
var reactDocs = require('react-docgen');
var path = require("path")
var fs = require("fs")

const src = fs.readFileSync(path.resolve(__dirname, "src", "Failing.tsx"), "utf8")

var componentInfo = reactDocs.parse(src);
console.log(componentInfo)
```

Error when parsing this File:

```
/Users/svenliebig/GitHub/react-docgen-test/node_modules/@babel/core/lib/transformation/normalize-file.js:209
    throw err;
    ^

SyntaxError: unknown: Unexpected token (11:4)

   9 |      * @memberof Props
  10 |      */
> 11 |     children: ReactNode
     |     ^
  12 |     yes: string
  13 | }
  14 |
    at Object.raise (/Users/svenliebig/GitHub/react-docgen-test/node_modules/@babel/parser/lib/index.js:6344:17)
    at Object.unexpected (/Users/svenliebig/GitHub/react-docgen-test/node_modules/@babel/parser/lib/index.js:7659:16)
    at Object.flowObjectTypeSemicolon (/Users/svenliebig/GitHub/react-docgen-test/node_modules/@babel/parser/lib/index.js:1584:12)
    at Object.flowParseObjectType (/Users/svenliebig/GitHub/react-docgen-test/node_modules/@babel/parser/lib/index.js:1478:12)
    at Object.flowParsePrimaryType (/Users/svenliebig/GitHub/react-docgen-test/node_modules/@babel/parser/lib/index.js:1736:21)
    at Object.flowParsePostfixType (/Users/svenliebig/GitHub/react-docgen-test/node_modules/@babel/parser/lib/index.js:1868:21)
    at Object.flowParsePrefixType (/Users/svenliebig/GitHub/react-docgen-test/node_modules/@babel/parser/lib/index.js:1888:19)
    at Object.flowParseAnonFunctionWithoutParens (/Users/svenliebig/GitHub/react-docgen-test/node_modules/@babel/parser/lib/index.js:1893:24)
    at Object.flowParseIntersectionType (/Users/svenliebig/GitHub/react-docgen-test/node_modules/@babel/parser/lib/index.js:1910:23)
    at Object.flowParseUnionType (/Users/svenliebig/GitHub/react-docgen-test/node_modules/@babel/parser/lib/index.js:1923:23)
```

Weird other behauviors too when i try to change it to an interface, get the same error without the comma, and completly NO TYPE when i have the commas.

This error accured me when i was using gatsby to parse some TypeScript files, where i wanted to stay with the type definitions. Any Ideas? I guess this is a bug, but probably i could have missed some configurations.

Thank you for reading this, you are awesome <3

**Comment by Sly321** [comment]
This is fixed in `"react-docgen": "5.0.1-beta"`, updating to this version solves the image
