### ISSUE TITLE
Does 5.2.0 support TS enum?

### ISSUE THREAD

**Issue by patricklafrance** [reactjs/react-docgen#429]
Hi,

I was wondering if version 5.2.0 support TS enum? I get the following error:

```
C:\Dev\10_poc\react-docgen\node_modules\@babel\core\lib\parser\index.js:95
    throw err;
    ^

SyntaxError: unknown: Unexpected reserved word 'enum' (22:0)

  20 | }
  21 | 
> 22 | enum DefaultEnum {
     | ^
  23 |   TopLeft = "top-left",
  24 |   TopRight = "top-right",
  25 |   TopCenter = "top-center",
    at Object.raise (C:\Dev\10_poc\react-docgen\node_modules\@babel\parser\lib\index.js:7013:17)
    at Object.checkReservedWord (C:\Dev\10_poc\react-docgen\node_modules\@babel\parser\lib\index.js:10371:14)
    at Object.parseIdentifierName (C:\Dev\10_poc\react-docgen\node_modules\@babel\parser\lib\index.js:10331:12)
    at Object.parseIdentifier (C:\Dev\10_poc\react-docgen\node_modules\@babel\parser\lib\index.js:10303:23)
    at Object.parseExprAtom (C:\Dev\10_poc\react-docgen\node_modules\@babel\parser\lib\index.js:9482:27)
    at Object.parseExprAtom (C:\Dev\10_poc\react-docgen\node_modules\@babel\parser\lib\index.js:464:22)
    at Object.parseExprAtom (C:\Dev\10_poc\react-docgen\node_modules\@babel\parser\lib\index.js:4116:20)
    at Object.parseExprSubscripts (C:\Dev\10_poc\react-docgen\node_modules\@babel\parser\lib\index.js:9219:23)
    at Object.parseMaybeUnary (C:\Dev\10_poc\react-docgen\node_modules\@babel\parser\lib\index.js:9199:21)
    at Object.parseExprOps (C:\Dev\10_poc\react-docgen\node_modules\@babel\parser\lib\index.js:9067:23) {
  pos: 343,
  loc: Position { line: 22, column: 0 },
  code: 'BABEL_PARSE_ERROR'
}
```

Code:

```
enum DefaultEnum {
  TopLeft = "top-left",
  TopRight = "top-right",
  TopCenter = "top-center",
}

interface MyTsComponentProps {
    defaultEnum: DefaultEnum;
}

export const MyTsComponent: FC<MyTsComponentProps> = ({ any }) => {
    return <div></div>
};
```

@babel/parser version is 7.8.3

Thank you,

Patrick

**Comment by danez** [comment]
It does, if you try to paste your code into https://reactcommunity.org/react-docgen/ and switch to typescript it works. 

How do you use react-docgen?
