### ISSUE TITLE
Error: null does not match type Pattern when parsing anonymous class component

### ISSUE THREAD

**Issue by RequireSun** [reactjs/react-docgen#472]
```jsx
import * as React from 'react';

interface IProps {
  value: string;
}

export default class extends React.Component<IProps> {
  render() {
    const { value } = this.props;
    return <div className='s-c-z-example'>{value}</div>;
  }
}
```

```bash
Error with path "./src/lib/index.tsx": Error: null does not match type Pattern
Error: null does not match type Pattern
    at PredicateType.BaseType.assert (/Users/bytedance/Workspace/Temp/semi-test/SCZExample/node_modules/ast-types/lib/types.js:14:19)
    at addPattern (/Users/bytedance/Workspace/Temp/semi-test/SCZExample/node_modules/ast-types/lib/scope.js:232:28)
    at recursiveScanChild (/Users/bytedance/Workspace/Temp/semi-test/SCZExample/node_modules/ast-types/lib/scope.js:205:13)
    at /Users/bytedance/Workspace/Temp/semi-test/SCZExample/node_modules/ast-types/lib/scope.js:176:17
    at /Users/bytedance/Workspace/Temp/semi-test/SCZExample/node_modules/ast-types/lib/types.js:683:22
    at Array.forEach (<anonymous>)
    at Object.eachField (/Users/bytedance/Workspace/Temp/semi-test/SCZExample/node_modules/ast-types/lib/types.js:682:31)
    at recursiveScanScope (/Users/bytedance/Workspace/Temp/semi-test/SCZExample/node_modules/ast-types/lib/scope.js:171:19)
    at recursiveScanChild (/Users/bytedance/Workspace/Temp/semi-test/SCZExample/node_modules/ast-types/lib/scope.js:227:13)
    at NodePath.<anonymous> (/Users/bytedance/Workspace/Temp/semi-test/SCZExample/node_modules/ast-types/lib/scope.js:140:17)
```

It seems that react-docgen consideres all the class component are named, so it went wrong when i provide an anonymous class component to it.

**Comment by JohnLouderback** [comment]
I am experiencing this same issue. @RequireSun Did you ever find a solution?

**Comment by danez** [comment]
This is a problem in `benjamn/ast-types`. I opened a PR there. benjamn/ast-types#467
