### ISSUE TITLE
Imported Default Prop Types

### ISSUE THREAD

**Issue by AlanFoster** [reactjs/react-docgen#63]
I seem to be having an issue with the following code -

```js
import React from 'react';
import DefaultChildComponent from './default-child-component.jsx';

const ParentComponent = React.createClass({
  getDefaultProps() {
    return {
      ChildComponent: DefaultChildComponent
    }
  },

  render() {
    return (
      <div>
        <this.props.ChildComponent foo={true} />
      </div>
    )
  }
});

export default ParentComponent;
```

This triggers the following error -

```shell
    throw (0, _pluginError2['default'])({
    ^
Error: [{type: ImportDefaultSpecifier, start: 34, end: 55, loc: [object Object], local: [object Object], id: null, name: null}] does not match type Printable
    at Type.Tp.assert (/Users/alanfoster/Documents/Shopkeep/backoffice/node_modules/ast-types/lib/types.js:56:15)
    at genericPrintNoParens (/Users/alanfoster/Documents/Shopkeep/backoffice/node_modules/recast/lib/printer.js:162:26)
    at genericPrint (/Users/alanfoster/Documents/Shopkeep/backoffice/node_modules/recast/lib/printer.js:148:33)
    at printRootGenerically (/Users/alanfoster/Documents/Shopkeep/backoffice/node_modules/recast/lib/printer.js:94:16)
    at maybeReprint (/Users/alanfoster/Documents/Shopkeep/backoffice/node_modules/recast/lib/printer.js:88:16)
    at print (/Users/alanfoster/Documents/Shopkeep/backoffice/node_modules/recast/lib/printer.js:75:29)
    at exports.printComments (/Users/alanfoster/Documents/Shopkeep/backoffice/node_modules/recast/lib/comments.js:324:22)
    at printWithComments (/Users/alanfoster/Documents/Shopkeep/backoffice/node_modules/recast/lib/printer.js:61:16)
    at print (/Users/alanfoster/Documents/Shopkeep/backoffice/node_modules/recast/lib/printer.js:66:20)
    at Printer.print (/Users/alanfoster/Documents/Shopkeep/backoffice/node_modules/recast/lib/printer.js:107:21)
```

**Comment by chrisege** [comment]
It's not ideal, but as a workaround, something like this will prevent a failure:
```javascript
const DefaultChild = props => <DefaultChildComponent {...props} />
```

and then:
```javascript
 getDefaultProps() {
    return {
      ChildComponent: DefaultChild
    }
  },
```
