### ISSUE TITLE
Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by MoOx** [reactjs/react-docgen#75]
```
TypeError: Cannot read property 'length' of undefined
    at NodePath.each (.../node_modules/ast-types/lib/path.js:82:25)
    at flowTypeHandler (.../node_modules/react-docgen/dist/handlers/flowTypeHandler.js:47:35)
    at .../node_modules/react-docgen/dist/parse.js:40:14
    at Array.forEach (native)
    at .../node_modules/react-docgen/dist/parse.js:39:14
    at Array.map (native)
    at executeHandlers (.../node_modules/react-docgen/dist/parse.js:37:31)
    at parse (.../node_modules/react-docgen/dist/parse.js:77:12)
    at Object.defaultParse [as parse] (.../node_modules/react-docgen/dist/main.js:65:33)
    at defaultPropsParser (.../node_modules/react-styleguidist/loaders/props.loader.js:12:20)
    at Object.module.exports (.../node_modules/react-styleguidist/loaders/props.loader.js:19:15)
    at WEBPACK_CORE_LOADER_EXECUTION (.../node_modules/webpack-core/lib/NormalModuleMixin.js:155:71)
    at runSyncOrAsync (.../node_modules/webpack-core/lib/NormalModuleMixin.js:155:93)
    at nextLoader (.../node_modules/webpack-core/lib/NormalModuleMixin.js:290:3)
    at .../node_modules/webpack-core/lib/NormalModuleMixin.js:259:5
    at Storage.finished (.../node_modules/webpack/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:38:16)
```

With the following file

```js
// @flow

import React from "react"
import Button, { isDefaultButton } from "../Button"
import type { Props as ButtonProps } from "../Button"
import Spinner from "../Spinner"

type Props = ButtonProps & {
  loading?: boolean,
  onAction?: Function,
}

/**
 * Button component
 */
const ActionButton = (props: Props): ReactElement => {
  const onAction = props.loading ? undefined : props.onAction

  return (
    <Button
      { ...props }
      { ...onAction && {
        onClick: onAction,
      } }
      disabled={ props.loading }
      disabledAffectColors={ false }
      labelPosition={ "before" }
      style={ { display: "inline-block" } }
    >
      {
        props.loading &&
          <Spinner
            color={ isDefaultButton(props) ? "#000" : "#fff" }
            style={ {
              verticalAlign: "middle",
              marginRight: "1rem",
            } }
          />
      }
    </Button>
  )
}

export default ActionButton
```

I suspect that the [intersection](http://flowtype.org/docs/union-intersection-types.html#intersection-example) is unsupported.

**Comment by MoOx** [comment]
It got this issue via react-styleguidist

**Comment by danez** [comment]
I'm currently out of town for 2 weeks, but will have a look as soon as I'm back and fix the exception.
Probably react-docgen won't be able to extract the correct types in this case, as parts of them are imported.

**Comment by MoOx** [comment]
Thanks for letting me know. No rush. Enjoy your time.
