### ISSUE TITLE
Internal server error: Argument must be Identifier, Literal, QualifiedTypeIdentifier or TSQualifiedName. Received 'TemplateLiteral'

### ISSUE THREAD

**Issue by yayapao** [reactjs/react-docgen#885]
After i have upgrade the storybook to 7.6.7, i caught the error `Internal server error: Argument must be Identifier, Literal, QualifiedTypeIdentifier or TSQualifiedName. Received 'TemplateLiteral'`, and storybook app cannot startup.

Then i tried to write a simple demo, and the error is still exist.

**.storybook/main.ts**
```ts

import { dirname, join } from "path";
// @ts-ignore
import type { StorybookConfig } from "@storybook/react-vite";
import { mergeConfig } from "vite";

const config: StorybookConfig = {
  stories: ["../src/**/*.mdx", "../src/**/*.stories.@(js|jsx|mjs|ts|tsx)"],
  addons: [
    getAbsolutePath("@storybook/addon-links"),
    getAbsolutePath("@storybook/addon-essentials"),
    getAbsolutePath("@storybook/addon-interactions"),
    // getAbsolutePath("@storybook/addon-mdx-gfm")
  ],
  framework: {
    name: "@storybook/react-vite",
    options: {
      legacyRootApi: true
    },
  },
  docs: {
    autodocs: "tag",
  },
  typescript: {
    // Overrides the default Typescript configuration to allow multi-package components to be documented via Autodocs.
    reactDocgen: 'react-docgen',
    skipBabel: true,
    check: false,
  },
  // enable builder
  core: {},
  async viteFinal(config, { configType }) {
    // customize the Vite config here
    return mergeConfig(config, {});
  },
};
export default config;

function getAbsolutePath(value: string): any {
  return dirname(require.resolve(join(value, "package.json")));
}

```

**test.stories.tsx**
```tsx
// Replace your-framework with the name of your framework
import type { Meta, StoryObj } from '@storybook/react';

import { TestEle } from '@nofun/ui';

const meta: Meta<typeof TestEle> = {
  component: TestEle,
};

export default meta;
type Story = StoryObj<typeof TestEle>;

//👇 Throws a type error it the args don't match the component props
export const Primary: Story = {
  args: {},
};
```

**TestEle.tsx**
```tsx
const TestEle = () => {
    return (
        <div>1</div>
    )
}

export { TestEle }
```

the error message:

```
11:17:55 AM [vite] Internal server error: Argument must be Identifier, Literal, QualifiedTypeIdentifier or TSQualifiedName. Received 'TemplateLiteral'
  Plugin: storybook:react-docgen-plugin
  File: /Users/yango/github/react/frontend-joys/packages/nofun-ui/dist/chunk-AUZFT565.mjs
      at getNameOrValue (/Users/yango/github/react/frontend-joys/node_modules/.pnpm/react-docgen@7.0.1/node_modules/react-docgen/dist/utils/getNameOrValue.js:48:9)
      at Object.enter (/Users/yango/github/react/frontend-joys/node_modules/.pnpm/react-docgen@7.0.1/node_modules/react-docgen/dist/utils/getMemberExpressionValuePath.js:83:100)
      at NodePath._call (/Users/yango/github/react/frontend-joys/node_modules/.pnpm/@babel+traverse@7.23.7/node_modules/@babel/traverse/lib/path/context.js:46:20)
      at NodePath.call (/Users/yango/github/react/frontend-joys/node_modules/.pnpm/@babel+traverse@7.23.7/node_modules/@babel/traverse/lib/path/context.js:36:17)
      at NodePath.visit (/Users/yango/github/react/frontend-joys/node_modules/.pnpm/@babel+traverse@7.23.7/node_modules/@babel/traverse/lib/path/context.js:82:31)
      at TraversalContext.visitQueue (/Users/yango/github/react/frontend-joys/node_modules/.pnpm/@babel+traverse@7.23.7/node_modules/@babel/traverse/lib/context.js:86:16)
      at TraversalContext.visitSingle (/Users/yango/github/react/frontend-joys/node_modules/.pnpm/@babel+traverse@7.23.7/node_modules/@babel/traverse/lib/context.js:65:19)
      at TraversalContext.visit (/Users/yango/github/react/frontend-joys/node_modules/.pnpm/@babel+traverse@7.23.7/node_modules/@babel/traverse/lib/context.js:109:19)
      at traverseNode (/Users/yango/github/react/frontend-joys/node_modules/.pnpm/@babel+traverse@7.23.7/node_modules/@babel/traverse/lib/traverse-node.js:22:17)
      at NodePath.visit (/Users/yango/github/react/frontend-joys/node_modules/.pnpm/@babel+traverse@7.23.7/node_modules/@babel/traverse/lib/path/context.js:88:52)
      at TraversalContext.visitQueue (/Users/yango/github/react/frontend-joys/node_modules/.pnpm/@babel+traverse@7.23.7/node_modules/@babel/traverse/lib/context.js:86:16)
      at TraversalContext.visitMultiple (/Users/yango/github/react/frontend-joys/node_modules/.pnpm/@babel+traverse@7.23.7/node_modules/@babel/traverse/lib/context.js:61:17)
      at TraversalContext.visit (/Users/yango/github/react/frontend-joys/node_modules/.pnpm/@babel+traverse@7.23.7/node_modules/@babel/traverse/lib/context.js:107:19)
      at traverseNode (/Users/yango/github/react/frontend-joys/node_modules/.pnpm/@babel+traverse@7.23.7/node_modules/@babel/traverse/lib/traverse-node.js:22:17)
      at NodePath.visit (/Users/yango/github/react/frontend-joys/node_modules/.pnpm/@babel+traverse@7.23.7/node_modules/@babel/traverse/lib/path/context.js:88:52)
      at TraversalContext.visitQueue (/Users/yango/github/react/frontend-joys/node_modules/.pnpm/@babel+traverse@7.23.7/node_modules/@babel/traverse/lib/context.js:86:16)
      at TraversalContext.visitSingle (/Users/yango/github/react/frontend-joys/node_modules/.pnpm/@babel+traverse@7.23.7/node_modules/@babel/traverse/lib/context.js:65:19)
      at TraversalContext.visit (/Users/yango/github/react/frontend-joys/node_modules/.pnpm/@babel+traverse@7.23.7/node_modules/@babel/traverse/lib/context.js:109:19)
      at traverseNode (/Users/yango/github/react/frontend-joys/node_modules/.pnpm/@babel+traverse@7.23.7/node_modules/@babel/traverse/lib/traverse-node.js:22:17)
      at NodePath.visit (/Users/yango/github/react/frontend-joys/node_modules/.pnpm/@babel+traverse@7.23.7/node_modules/@babel/traverse/lib/path/context.js:88:52)
      at TraversalContext.visitQueue (/Users/yango/github/react/frontend-joys/node_modules/.pnpm/@babel+traverse@7.23.7/node_modules/@babel/traverse/lib/context.js:86:16)
      at TraversalContext.visitMultiple (/Users/yango/github/react/frontend-joys/node_modules/.pnpm/@babel+traverse@7.23.7/node_modules/@babel/traverse/lib/context.js:61:17)
      at TraversalContext.visit (/Users/yango/github/react/frontend-joys/node_modules/.pnpm/@babel+traverse@7.23.7/node_modules/@babel/traverse/lib/context.js:107:19)
      at traverseNode (/Users/yango/github/react/frontend-joys/node_modules/.pnpm/@babel+traverse@7.23.7/node_modules/@babel/traverse/lib/traverse-node.js:22:17)
      at NodePath.visit (/Users/yango/github/react/frontend-joys/node_modules/.pnpm/@babel+traverse@7.23.7/node_modules/@babel/traverse/lib/path/context.js:88:52)
      at TraversalContext.visitQueue (/Users/yango/github/react/frontend-joys/node_modules/.pnpm/@babel+traverse@7.23.7/node_modules/@babel/traverse/lib/context.js:86:16)
      at TraversalContext.visitSingle (/Users/yango/github/react/frontend-joys/node_modules/.pnpm/@babel+traverse@7.23.7/node_modules/@babel/traverse/lib/context.js:65:19)
      at TraversalContext.visit (/Users/yango/github/react/frontend-joys/node_modules/.pnpm/@babel+traverse@7.23.7/node_modules/@babel/traverse/lib/context.js:109:19)
      at traverseNode (/Users/yango/github/react/frontend-joys/node_modules/.pnpm/@babel+traverse@7.23.7/node_modules/@babel/traverse/lib/traverse-node.js:22:17)
      at NodePath.visit (/Users/yango/github/react/frontend-joys/node_modules/.pnpm/@babel+traverse@7.23.7/node_modules/@babel/traverse/lib/path/context.js:88:52)
      at TraversalContext.visitQueue (/Users/yango/github/react/frontend-joys/node_modules/.pnpm/@babel+traverse@7.23.7/node_modules/@babel/traverse/lib/context.js:86:16)
      at TraversalContext.visitMultiple (/Users/yango/github/react/frontend-joys/node_modules/.pnpm/@babel+traverse@7.23.7/node_modules/@babel/traverse/lib/context.js:61:17)
      at TraversalContext.visit (/Users/yango/github/react/frontend-joys/node_modules/.pnpm/@babel+traverse@7.23.7/node_modules/@babel/traverse/lib/context.js:107:19)
      at traverseNode (/Users/yango/github/react/frontend-joys/node_modules/.pnpm/@babel+traverse@7.23.7/node_modules/@babel/traverse/lib/traverse-node.js:22:17)
      at NodePath.visit (/Users/yango/github/react/frontend-joys/node_modules/.pnpm/@babel+traverse@7.23.7/node_modules/@babel/traverse/lib/path/context.js:88:52)
      at TraversalContext.visitQueue (/Users/yango/github/react/frontend-joys/node_modules/.pnpm/@babel+traverse@7.23.7/node_modules/@babel/traverse/lib/context.js:86:16)
      at TraversalContext.visitSingle (/Users/yango/github/react/frontend-joys/node_modules/.pnpm/@babel+traverse@7.23.7/node_modules/@babel/traverse/lib/context.js:65:19)
      at TraversalContext.visit (/Users/yango/github/react/frontend-joys/node_modules/.pnpm/@babel+traverse@7.23.7/node_modules/@babel/traverse/lib/context.js:109:19)
      at traverseNode (/Users/yango/github/react/frontend-joys/node_modules/.pnpm/@babel+traverse@7.23.7/node_modules/@babel/traverse/lib/traverse-node.js:22:17)
      at NodePath.visit (/Users/yango/github/react/frontend-joys/node_modules/.pnpm/@babel+traverse@7.23.7/node_modules/@babel/traverse/lib/path/context.js:88:52)
      at TraversalContext.visitQueue (/Users/yango/github/react/frontend-joys/node_modules/.pnpm/@babel+traverse@7.23.7/node_modules/@babel/traverse/lib/context.js:86:16)
      at TraversalContext.visitMultiple (/Users/yango/github/react/frontend-joys/node_modules/.pnpm/@babel+traverse@7.23.7/node_modules/@babel/traverse/lib/context.js:61:17)
      at TraversalContext.visit (/Users/yango/github/react/frontend-joys/node_modules/.pnpm/@babel+traverse@7.23.7/node_modules/@babel/traverse/lib/context.js:107:19)
      at traverseNode (/Users/yango/github/react/frontend-joys/node_modules/.pnpm/@babel+traverse@7.23.7/node_modules/@babel/traverse/lib/traverse-node.js:22:17)
      at NodePath.visit (/Users/yango/github/react/frontend-joys/node_modules/.pnpm/@babel+traverse@7.23.7/node_modules/@babel/traverse/lib/path/context.js:88:52)
      at TraversalContext.visitQueue (/Users/yango/github/react/frontend-joys/node_modules/.pnpm/@babel+traverse@7.23.7/node_modules/@babel/traverse/lib/context.js:86:16)
      at TraversalContext.visitSingle (/Users/yango/github/react/frontend-joys/node_modules/.pnpm/@babel+traverse@7.23.7/node_modules/@babel/traverse/lib/context.js:65:19)
      at TraversalContext.visit (/Users/yango/github/react/frontend-joys/node_modules/.pnpm/@babel+traverse@7.23.7/node_modules/@babel/traverse/lib/context.js:109:19)
      at traverseNode (/Users/yango/github/react/frontend-joys/node_modules/.pnpm/@babel+traverse@7.23.7/node_modules/@babel/traverse/lib/traverse-node.js:22:17)
      at NodePath.visit (/Users/yango/github/react/frontend-joys/node_modules/.pnpm/@babel+traverse@7.23.7/node_modules/@babel/traverse/lib/path/context.js:88:52)
Argument must be Identifier, Literal, QualifiedTypeIdentifier or TSQualifiedName. Received 'TemplateLiteral'
```

**Comment by yayapao** [comment]
After read [The auto-generated documentation is not showing up in a monorepo setup](https://storybook.js.org/docs/writing-docs/autodocs#the-auto-generated-documentation-is-not-showing-up-in-a-monorepo-setup) i change the component import way and it works.

**test.stories.tsx**

```tsx
// Replace your-framework with the name of your framework
import type { Meta, StoryObj } from '@storybook/react';

import { TestEle } from '@nofun/ui/src/TestEle';

const meta: Meta<typeof TestEle> = {
  component: TestEle,
};

export default meta;
type Story = StoryObj<typeof TestEle>;

//👇 Throws a type error it the args don't match the component props
export const Primary: Story = {
  args: {},
};
```

**Comment by danez** [comment]
duplicate of #876
