### ISSUE TITLE
Example not working (out of the box)

### ISSUE THREAD

**Issue by Moezalez** [reactjs/react-docgen#90]
Just tried to naively run the example, and I get:
`buildDocs.sh: command not found`

MacOS

**Comment by fkling** [comment]
Did you try to add execution permissions, i.e. `chmod +x buildDocs.sh`?

**Comment by kevinSuttle** [comment]
I just ran `./buildDocs.sh` and it never completes. OSX 10.11.5 (15F34)

**Comment by i-a-n** [comment]
@kevinSuttle - buildDocs.sh expects JSON input, it doesn't run independently. Try this:

`$ react-docgen components/* | ./buildDocs.sh`

...Replacing `components/*` with the path to your components directory.

**Comment by kevinSuttle** [comment]
Thanks.

**Comment by kevinSuttle** [comment]
```
~/Code/react-docgen-master/example
❯ react-docgen components/Component.js | ./buildDocs.sh
/Users/kevinSuttle/Code/react-docgen-master/example/generateMarkdown.js:65
    Object.keys(props).sort().map(function(propName) {
           ^

TypeError: Cannot convert undefined or null to object
    at generateProps (/Users/kevinSuttle/Code/react-docgen-master/example/generateMarkdown.js:65:12)
    at generateMarkdown (/Users/kevinSuttle/Code/react-docgen-master/example/generateMarkdown.js:75:5)
    at buildDocs (/Users/kevinSuttle/Code/react-docgen-master/example/buildDocs.sh:29:20)
    at Socket.<anonymous> (/Users/kevinSuttle/Code/react-docgen-master/example/buildDocs.sh:22:3)
    at emitNone (events.js:91:20)
    at Socket.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:934:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```
Note that I had to install react-docgen globally first...

**Comment by fkling** [comment]
@kevinSuttle: See https://github.com/reactjs/react-docgen/issues/94 .
